# Generated by Django 5.0.6 on 2024-08-21 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='trainingprogram',
            name='program_id',
        ),
        migrations.AddField(
            model_name='trainingprogram',
            name='program',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='program_planner.program'),
            preserve_default=False,
        ),
    ]
