# Generated by Django 5.0.6 on 2024-08-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program_planner', '0002_pdffile_remove_trainingprogram_program_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='index',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
