# Generated by Django 5.0.6 on 2024-06-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='groupID',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Exercise group id'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='groupName',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Exercise group name'),
        ),
    ]
