# Generated by Django 5.0.6 on 2024-08-19 17:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('ingredients', models.JSONField()),
                ('instructions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('nutrition_facts', models.JSONField()),
            ],
        ),
    ]
